name: Build Image using Containerfile
on: [push]
env:
    IMAGE_NAME: vanilla-os 
    IMAGE_TAGS: 22.10r7 ${{ github.sha }}
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      # Checkout push-to-registry action github repository
    - name: Checkout Push to Registry action
    - uses: actions/checkout@v3

    - name: Buildah Action
      uses: redhat-actions/buildah-build@v2
      with:
       image: ${{ env.IMAGE_NAME }}
       tags: ${{ env.IMAGE_TAGS }}
       oci: true
       containerfiles: |
         ./Containerfile

      # Push the image to GHCR (Image Registry)
    - name: Push To GHCR
      uses: ./
      id: push
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        extra-args: |
          --disable-content-trust

    - name: Echo outputs
      run: |
        echo "${{ toJSON(steps.push.outputs) }}"