name: Build Image using Containerfile
on:
  push:
    tags:
      - '*'    
env:
    IMAGE_NAME: vanilla-os 
    IMAGE_TAGS: ${{ github.ref_name}} latest
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    DOCKER_REGISTRY: docker.io/${{ github.repository_owner }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}
    DOCKER_USER: ${{ secrets.DOCKER_USER }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      # Checkout push-to-registry action github repository
    - name: Checkout Push to Registry action
      uses: actions/checkout@v3

    - name: Buildah Action
      id: build-action
      uses: redhat-actions/buildah-build@v2
      with:
       image: ${{ env.IMAGE_NAME }}
       tags: ${{ env.IMAGE_TAGS }}
       oci: true
       containerfiles: |
         ./Containerfile

      # Push the image to GHCR (Image Registry)
    - name: Push To GHCR
      uses: redhat-actions/push-to-registry@v2
      id: push
      with:
        image: ${{ steps.build-action.outputs.image }}
        tags: ${{ steps.build-action.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        extra-args: |
          --disable-content-trust

      # Push the image to docker
    - name: Push To docker
      uses: redhat-actions/push-to-registry@v2
      id: pushdocker
      with:
        image: ${{ steps.build-action.outputs.image }}
        tags: ${{ steps.build-action.outputs.tags }}
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        extra-args: |
          --disable-content-trust
    - name: Echo outputs
      run: |
        echo "${{ toJSON(steps.push.outputs) }}"
        echo "${{ toJSON(steps.pushocker.outputs) }}"